### ISSUE TITLE
Is there a way to hide the cosmetics of the Artifacts in 1.16.5?

### ISSUE THREAD

**Issue by Dr-Tarantula** [florensie/artifacts-fabric#55] opened 2022-01-30 03:10 UTC
My friends and I are playing on a 1.16.5 Fabric Minecraft server, and we like the benefits of having the Artifacts on, however we want the ability to hide the  artifacts for RP purposes. Is there a change that can be easily made to the config, or a feature that we are unable to find?

**Comment by florensie** [comment] 2022-01-30 11:32
Duplicate of #31

**Closed by florensie** 2022-01-30 11:32 UTC
Labels: enhancement
