### ISSUE TITLE
Thorns necklace crashes dedicated server when attempting to attack Shulker Bullets

### ISSUE THREAD

**Issue by dandin87** [florensie/artifacts-fabric#10] opened 2020-11-20 21:18 UTC
AoF3 2.4.3 Minecraft 1.16.4
AoF3 NA public server
https://hastebin.com/nicinanazi.yaml

**Comment by florensie** [comment] 2020-11-21 18:32
I'm a bit stumped with this one, I can't reproduce it and the crash report sadly doesn't help much. I put a release up on CF that might fix this. Please let me know if it helps.

**Comment by florensie** [comment] 2020-11-28 00:21
I'm closing this for now. Don't hesitate to let me know if the issue persists.

**Closed by florensie** 2020-11-28 00:21 UTC
Labels: bug

**Comment by dandin87** [comment] 2020-12-01 19:45
Server crash again. This time it was the flame pendant. Server will be updating this week to the newer version, this was Artifacts v1.1.0 
https://hastebin.com/ginerudece.yaml

**Comment by florensie** [comment] 2020-12-02 15:27
Not sure why it didn't occur to me to check the other pendants. Should hopefully be all fixed in 2.0.2.
