### ISSUE TITLE
[Feature Request] Durability + Blacklist

### ISSUE THREAD

**Issue by itsdinkd** [florensie/artifacts-fabric#62] opened 2022-05-15 19:12 UTC
**Is your feature request related to a problem? Please describe.**
Yes. as a modpack creator, i'd like to fine tune each individual artifact, like how its done in Aritifacts for Forge. This way I can make artifacts an actual resource, when players can use them only when needed. (Speaking about durability on artifacts)

**Describe the solution you'd like**
Set up artifacts for fabric the same way as on Artifacts for forge allowing people to enable the Durability System as well as the Blacklist system. For the fabric mod, I had to dig through every single loot table just to remove the artifacts I do not want in the game, whereas in forge; all I have to do is add it to the blacklist that is shipped with the mod on the config.

**Comment by florensie** [comment] 2022-06-14 18:45
Duplicate of #44

**Closed** 2022-06-14 18:45 UTC
Labels: enhancement

**Comment by itsdinkd** [comment] 2022-06-14 23:49
Dang that was almost a year ago :D any plans on doing it?

**Comment by florensie** [comment] 2022-06-15 07:18
Absolutely, but there are plans for a little re-do of the Forge configs too, so I don't want to rush this out and then have to change it again.
