### ISSUE TITLE
1.16.5 trinket slot swapping bug

### ISSUE THREAD

**Issue by superon** [florensie/artifacts-fabric#54] opened 2022-01-29 16:52 UTC
![Screen Shot 2022-01-29 at 14 19 17](https://user-images.githubusercontent.com/5957924/151667177-80a24178-d6d0-4f15-bbe1-13a66aec4c9c.png)

https://user-images.githubusercontent.com/5957924/151667756-41d7795f-0174-4aa9-85d4-8c77582c4f47.mov

i've not a clue why this is/what caused this to happen.
could be something else of course, i just don't know where to start looking.
i have tried loading a the server without any other mods that require/use trinkets and this behaviour persists
works fine in sp, this appears to be just mp issue
artifacts-4.0.3+fabric
Cardinal-Components-API-2.8.3
cloth-config-4.13.49-fabric
fabric-api-0.42.0+1.16
trinkets-2.6.7

**Comment by florensie** [comment] 2022-02-22 18:08
Probably a duplicate of #20 

It's a bug likely in Trinkets itself, which never got found/resolved. Neither Artifacts or Trinkets are getting updates for 1.16 anymore.

**Closed by florensie** 2022-02-22 18:08 UTC
Labels: bug
