### ISSUE TITLE
failure to launch on modpack 1.1.

### ISSUE THREAD

**Issue by superon** [florensie/artifacts-fabric#48] opened 2021-11-03 13:28 UTC
**Describe the bug**
modpack fails to launch with:
https://pastebin.com/NMbhHdYv

**To Reproduce**
Steps to reproduce the behaviour:
1. click launch

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Minecraft: [1.16.5]
 - Fabric API: [fabric-api-0.41.3+1.16]
 - Artifacts: [artifacts-4.0.2+fabric]
 - Trinkets: [trinkets-2.6.7]
 - [idk if any of the other mods are relevant]
 - other info maybe more relevant: the game launches fine with artifacts-3.2.1+fabric

**Comment by florensie** [comment] 2021-11-03 13:43
Duplicate of #46

**Closed by florensie** 2021-11-03 13:43 UTC
Labels: bug, duplicate, invalid

**Comment by superon** [comment] 2021-11-08 21:58
i don't have ExpandAbility downloaded separate

**Comment by florensie** [comment] 2021-11-09 11:22
That doesn't matter, you still have it when you install Artifacts because it's included.
