### ISSUE TITLE
[Feature Request] Kitty Slippers Compatibility for Creeper Overhaul 

### ISSUE THREAD

**Issue by Cymophic** [florensie/artifacts-fabric#73] opened 2022-08-12 13:23 UTC
The mod adds more variations to the creeper. Normal creepers from the mod are scared of the slippers, but the other ones aren't. I would like to ask for a compat.

**Comment by florensie** [comment] 2022-08-12 18:35
duplicate of #68

**Closed** 2022-08-12 18:35 UTC
Labels: enhancement
